from rsf.proj import *

#   PARA UMA MATRIZ QUADRADA

samples_quad = 100
origin_quad = -((samples_quad - 2) / 2)

formula_quad = "(x1/2)^2+(x2/2)^2"

Flow('paraboloide', None,
     'math n1=%d n2=%d o1=%f o2=%f output="%s"' %
     (samples_quad, samples_quad, origin_quad, origin_quad, formula_quad))

Result('para_graph', 'paraboloide',
     'grey wheretitle=top title="paraboloide-grey" scalebar=y color=j')

Result('para_graph2', 'paraboloide', 
     'contour wheretitle=top title="paraboloide-contour" nc=45 plotfat=5 plotcol=2')

#   PARA UMA MATRIZ RETANGULAR

samples_ret = [101, 51]
origin_ret = [-(samples_ret[0]-2) / 2, -(samples_ret[1]-2) / 2]


formula_ret  = formula_quad

Flow('paraboloide_ret', None, 
     'math n1=%d n2=%d o1=%f o2=%f output="%s"' %
     (samples_ret[0], samples_ret[1], origin_ret[0], origin_ret[1], formula_ret))

Result('para_graph_ret-grey', 'paraboloide_ret',
     'grey wheretitle=top title="paraboloide_ret" scalebar=y color=j')

Result('para_graph2_ret', 'paraboloide_ret', 
     'contour wheretitle=top title="paraboloide_ret-contour" nc=45 plotfat=5 plotcol=2')

End()